version: '3'
services:
    client:
        image: node:12.18.1
        user: root
        working_dir: /app/src/client
        command: npm run develop
        tty: true
        environment:
            ENV: development
            NODE_ENV: development
            ENABLE_GATSBY_REFRESH_ENDPOINT: 1
            SERVER_URL: http://cms:1337
            SERVER_OVERWRITE: http://cms:1337
        expose:
            - "8000"
        ports:
            - 0.0.0.0:8000:8000
        volumes:
            - .:/app
            - node_modules_client:/app/src/client/node_modules
        links:
            - cms
        depends_on:
            - cms

volumes:
    node_modules_client: