version: '3'
services:
  cms:
    image: node:10.11.0
    user: root
    working_dir: /app/src/cms
    command: npm run start
    tty: true
    expose:
      - "3000"
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cms
      DB_PORT: 5432
      PGDATA: /var/lib/postgresql/data/db/
    ports:
      - 0.0.0.0:5432:5432
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data/db

volumes:
  node_modules:
  db:
