version: '3'
services:
  client:
    image: node:12.18.1
    user: root
    working_dir: /app/src/client
    command: npm run develop
    tty: true
    environment:
      ENV: development
      NODE_ENV: development
      ENABLE_GATSBY_REFRESH_ENDPOINT: 1
      SERVER_URL: http://cms:1337
      SERVER_OVERWRITE: http://cms:1337
    expose:
      - "8000"
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - .:/app
      - node_modules_client:/app/src/client/node_modules
    links:
      - cms
    depends_on:
      - cms

  cms:
    image: node:12.18.1
    user: root
    working_dir: /app/src/cms
    command: npm run develop
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
    tty: true
    expose:
      - "1337"
    ports:
      - 0.0.0.0:1337:1337
    volumes:
      - .:/app
      - node_modules_cms:/app/src/cms/node_modules
    links:
      - db
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cms
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - 0.0.0.0:27017-27019:27017-27019
    expose:
      - "27017-27019"
    volumes:
      - ./ops/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db:/data/db

volumes:
  node_modules_cms:
  node_modules_client:
  db:
