version: '3'
services:
  client:
    image: node:12.18.1
    user: root
    working_dir: /app/src/client
    command: npm run develop
    tty: true
    environment:
      ENV: production
    expose:
      - "8000"
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - .:/app
      - node_modules_client:/app/src/client/node_modules
    links:
      - cms
    depends_on:
      - cms

  cms:
    image: node:12.18.1
    user: root
    working_dir: /app/src/cms
    command: npm run start
    environment:
      NODE_ENV: production
    tty: true
    expose:
      - "1337"
    ports:
      - 0.0.0.0:1337:1337
    volumes:
      - .:/app
      - node_modules_cms:/app/src/cms/node_modules
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: cms
      DB_PORT: 5432
      PGDATA: /var/lib/postgresql/data/db/
    ports:
      - 0.0.0.0:5432:5432
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data/db

volumes:
  node_modules_cms:
  node_modules_client:
  db:
