apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: client
  strategy:
    type: Recreate
  template:
    metadata:
      name: client
      labels:
        name: client
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: client
          image: 675468650888.dkr.ecr.eu-west-1.amazonaws.com/website_cms:latest
          imagePullPolicy: Always
          workingDir: /app/src/client
          command: ["npm"]
          args: ["run", "develop"]
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "250Mi"
              cpu: "0.05"
            limits:
              memory: "500Gi"
              cpu: "0.35"
          tty: true
          workingDir: /app/src/client
          env:
            - name: CMS_USERNAME
              value: "jwnwilson"
            - name: CMS_PASSWORD
              value: "$J9Z9dYi*AP^"
            - name: SERVER_URL
              value: http://cms:1337
            - name: SERVER_OVERWRITE
              value: http://cms:1337
            - name: ENABLE_GATSBY_REFRESH_ENDPOINT
              value: "1"
      restartPolicy: Always
      volumes:
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    name: client
spec:
  ports:
    - name: "client"
      port: 8000
      targetPort: 8000
  selector:
    name: client
  type: NodePort
status:
  loadBalancer: {}
