apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cms
  strategy:
    type: Recreate
  template:
    metadata:
      name: server
      labels:
        name: cms
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: server
          resources:
            limits:
              cpu: 1
              memory: "2000Mi"
            requests:
              cpu: 1
              memory: "2000Mi"
          image: 675468650888.dkr.ecr.eu-west-1.amazonaws.com/website_cms:latest
          imagePullPolicy: Always
          command: ["npm"]
          args: ["run", "start"]
          ports:
            - containerPort: 1337
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.05"
            limits:
              memory: "1Gi"
              cpu: "0.35"
          tty: true
          workingDir: /app/src/cms
          env:
            - name: ENV
              value: prod
            - name: NODE_ENV
              value: production
            - name: ACCESS_KEY
              value: AKIAZ2RIRVGEFTXHOXFW
            - name: SECRET_KEY
              value: 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
            - name: DATABASE_HOST
              value: db
            - name: CMS_USERNAME
              value: jwnwilson
            - name: CMS_PASSWORD
              value: $J9Z9dYi*AP^
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: cms
  labels:
    name: cms
spec:
  ports:
    - name: "cms"
      port: 1337
      targetPort: 1337
  selector:
    name: cms
  type: NodePort
status:
  loadBalancer: {}