apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - jwnwilson-kube.co.uk
    - {{CMS}}.jwnwilson-kube.co.uk
    - {{PREVIEW}}.jwnwilson-kube.co.uk
    secretName: jwnwilson-kube-co-uk-tls
  rules:
  - host: jwnwilson-kube.co.uk
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
  - host: {{CMS}}.jwnwilson-kube.co.uk
    http:
      paths:
      - backend:
          serviceName: cms
          servicePort: 1337
  - host: {{PREVIEW}}.jwnwilson-kube.co.uk
    http:
      paths:
      - backend:
          serviceName: client
          servicePort: 8000
