apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - jwnwilson.co.uk
    - cms.jwnwilson.co.uk
    - client.jwnwilson.co.uk
    secretName: jwnwilson-co-uk-tls
  rules:
  - host: jwnwilson.co.uk
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
  - host: cms.jwnwilson.co.uk
    http:
      paths:
      - backend:
          serviceName: cms
          servicePort: 1337
  - host: preview.jwnwilson.co.uk
    http:
      paths:
      - backend:
          serviceName: client
          servicePort: 8000
