apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  # annotations:
  #   kubernetes.io/tls-acme: "true"
  #   ingress.kubernetes.io/ssl-redirect: "True"
  #   kubernetes.io/ingress.allow-http: "false"
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  #   certmanager.k8s.io/acme-http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - jwnwilson.co.uk
    #secretName: letsencrypt-prod 
  rules:
  - host: cms.jwnwilson.co.uk
    http:
      paths:
      - backend:
          serviceName: cms
          servicePort: 1337
  - host: client.jwnwilson.co.uk
    http:
      paths:
      - backend:
          serviceName: client
          servicePort: 8000
