apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      cpu: 0.1
      memory: "250Mi"
    defaultRequest:
      cpu: 0.1
      memory: "250Mi"
    type: Container